### ISSUE TITLE
非根目录

### ISSUE THREAD

**Issue by webPorter** [helloxz/onenav#1]
不是根目录无法登录，有谁知道怎么解决吗？

**Comment by helloxz** [comment]
提示什么，页面不存在吗？报错信息发出来看看。

**Comment by webPorter** [comment]
![image](https://user-images.githubusercontent.com/37259749/104111351-cd636e00-531b-11eb-876b-0795dee7d3f2.png)
界面没有什么问题，就是点击登录没有反应

**Comment by webPorter** [comment]
![2d1919c82f3338518b9ad36bc170d8a](https://i.niupic.com/images/2021/01/10/99mP.png)
页面的显示没有问题，也没有报错，但是点击登录按钮没有反应。

**Comment by helloxz** [comment]
1. 检查config.php是否按要求正确设置
2. 可以用浏览器F12看下登录的时候Network加载报错没有
3. 如果依然不行，请加我QQ：337003006，提供地址、帐号、密码我这边测试下。

**Comment by 2291200076** [comment]
@helloxz 
controller目录下，index.php文件内13-17行的函数
`
//如果已经登录，直接跳转
if( $cookie == $key ){
    header('location:index.php?c=admin');
    exit;
}
`
这里有问题，`location:index.php?c=admin`会跳转到域名根目录的index.php

**Comment by 2291200076** [comment]
`header('location:index.php?c=admin');`
可以改成
`header('location:'.dirname($_SERVER['PHP_SELF']).'index.php?c=admin');`

**Comment by 2291200076** [comment]
比如
`header('location:index.php?c=admin');`
就可以改成
`header('location:'.dirname($_SERVER['PHP_SELF']).'/index.php?c=admin');`
其实这个项目完全可以部署在非根目录下的，但是代码中都指向了网站根目录的index.php，稍作修改即可

**Comment by webPorter** [comment]
已经解决，谢谢大佬
[参考](https://github.com/helloxz/onenav/issues/3)

**Comment by webPorter** [comment]
添加的书签点击后还是会跳到根目录，比如http://index/index.php?c=click&id=1，实际上应该为http://index/子目录/index.php?c=click&id=1
望大佬再帮忙看看

**Comment by 2291200076** [comment]
> 添加的书签点击后还是会跳到根目录，比如[http://index/index.php?c=click&id=1，实际上应该为http://index/子目录/index.php?c=click&id=1](http://index/index.php?c=click&id=1%EF%BC%8C%E5%AE%9E%E9%99%85%E4%B8%8A%E5%BA%94%E8%AF%A5%E4%B8%BAhttp://index/%E5%AD%90%E7%9B%AE%E5%BD%95/index.php?c=click&id=1)
> 望大佬再帮忙看看

onenav/templates/default/index.php
这个文件第128行
```
<a href="/index.php?c=click&id=<?php echo $link['id']; ?>" target="_blank" title = "<?php echo $link['description']; ?>">
```
在/index.php前面加一个点，即
```
<a href="./index.php?c=click&id=<?php echo $link['id']; ?>" target="_blank" title = "<?php echo $link['description']; ?>">
```
![image](https://user-images.githubusercontent.com/16949192/104836385-97f4ec80-58e8-11eb-94e7-e2f7dc8d0e75.png)

**Comment by webPorter** [comment]
ok, 已经解决，谢谢
