### ISSUE TITLE
希望前台能支持拖拽排序，二级导航横排选项

### ISSUE THREAD

**Issue by sfdzkj** [helloxz/onenav#100]
希望前台能支持拖拽排序，二级导航合并横排选项

**Comment by sfdzkj** [comment]
二级导航  栏目合并。横排点击展示栏目下内容

**Comment by helloxz** [comment]
0.9.37版本的`default2`主题已经支持拖拽排序，导航合并不够直接高效，暂时不会支持，后续新主题可能会考虑。
