### ISSUE TITLE
！！！添加链接接口报错，提示请先生成SecretKey（请求token是正确的）

### ISSUE THREAD

**Issue by kts168** [helloxz/onenav#103]
当前版本：v0.9.25-20221107

请求
curl --location --request POST 'https://onenav.xxx.xxx/index.php?c=api&method=add_link' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'token=xxxxxxxxxx' \
--data-urlencode 'url=https://www.xiaoz.me' \
--data-urlencode 'title=小z博客' \
--data-urlencode 'fid=1' \
--data-urlencode 'weight=0' \
--data-urlencode 'property=0' \
--data-urlencode 'description='

返回
{
    "code": -2000,
    "err_msg": "请先生成SecretKey！"
}

**Comment by kts168** [comment]
接口文档地址
https://doc.xiaoz.me/books/onenav/page/6ea9a

**Comment by helloxz** [comment]
参考下这个文档：https://doc.xiaoz.me/books/onenav/page/token
在`0.9.19`及之后的版本需要从后台先生成`SecretKey`，然后用计算Token去请求API

**Comment by kts168** [comment]
问题已解决，多谢
