### ISSUE TITLE
docker部署的从老版本升级到最新版的容器报错

### ISSUE THREAD

**Issue by ltkun** [helloxz/onenav#122]
[error] 13#13: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  require(): Failed opening required 'templates//index.php' (include_path='.:/usr/share/php7') in /data/wwwroot/default/controller/index.php on line 257" while reading response header from upstream, client: 10.6.0.5, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "........:58080"

**Comment by helloxz** [comment]
你是哪个版本升级到哪个版本？
