### ISSUE TITLE
docker缺失IPV6支持

### ISSUE THREAD

**Issue by jackadam1981** [helloxz/onenav#124]
调试半天，始终无法使用ipv6访问。
进入容器，发现nginx监听，没有监听ipv6。
请更新

**Comment by jackadam1981** [comment]
FROM helloz/onenav

RUN sed -i "/  listen 80;/a\  listen [::]:80;" /etc/nginx/conf.d/site.conf

**Comment by helloxz** [comment]
好的，镜像构建代码在这里：[https://github.com/helloxz/docker-onenav](https://github.com/helloxz/docker-onenav)

你可以先自行打包一个镜像来支持IPV6，后续新的镜像我也将支持IPV6

**Comment by jackadam1981** [comment]
是的，我已经用重新打包解决了问题。
随着IPV4枯竭，ipv6，应该作为默认支持了。
我3条光纤，联通一条，ipv4，公网，电信两条，老的，给了ipv4公网，新的，没有ipv4公网，折腾来折腾去，ipv6了。
过渡期，难呀。

**Comment by youppgd** [comment]
> FROM helloz/onenav
> 
> RUN sed -i "/ listen 80;/a\ listen [::]:80;" /etc/nginx/conf.d/site.conf

感谢！
