### ISSUE TITLE
开发环境-快速运行本项目的办法

### ISSUE THREAD

**Issue by jingjingxyk** [helloxz/onenav#126]
1. 下载 PHP 运行时  （看以前的ISSUES，好像不支持 PHP 8） 
```shell
curl -Lo php-7.4.30-static-bin-x86_64.tar.gz  https://dl.zhamao.xin/php-bin/file/php-7.4.30-static-bin-x86_64.tar.gz

tar -zxvf  php-7.4.30-static-bin-x86_64.tar.gz 

```
> 解压后得到 `php` 运行时

2.  运行本项目
```shell

./php -S 0.0.0.0:8000 -t onenav

```
3. 浏览器运行访问
```text

http://127.0.0.1:8000

```

PHP 运行时（实际就是PHP静态编译解释器）
 构建来源参考：
 1. https://github.com/swoole/swoole-src/releases
 2. https://github.com/swoole/swoole-cli.git
 3. https://github.com/crazywhalecc/static-php-cli.git
 4. https://dl.zhamao.xin/php-bin/file/

缘由：快速使用本项目

**Comment by helloxz** [comment]
用Docker似乎要更方便一些，参考：https://github.com/helloxz/docker-onenav
