### ISSUE TITLE
发现不支持http连接，只支持https的。（续）

### ISSUE THREAD

**Issue by lxtnew** [helloxz/onenav#129]
添加一个http链接： http://192.168.9.20

然后使用 curl 进行测试：

 curl -v -k "https://bookmark.mysite.org/index.php?c=click&id=36"
* About to connect() to bookmark.mysite.org port 443 (#0)
* Connected to bookmark.mysite.org port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* warning: ignoring value of ssl.verifyhost
* skipping SSL peer certificate verification
* SSL connection using TLS_RSA_WITH_AES_256_CBC_SHA
> GET /index.php?c=click&id=36 HTTP/1.1
> User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2
> Host: bookmark.mysite.org
> Accept: */*
>
< HTTP/1.1 302 Found
< Server: nginx/1.23.1
< Date: Sat, 28 Jan 2023 01:35:25 GMT
< Content-Type: text/html; charset=Utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/7.3.33
< location: https://192.168.9.20
<
* Connection #0 to host bookmark.mysite.org left intact
* Closing connection #0

可以发现返回的 location 指向变成 https 了。

**Comment by helloxz** [comment]
检查下是否是添加的时候就填写的`https://192.168.9.20/`

**Comment by lxtnew** [comment]
的确是添加的 http://192.168.9.20

**Comment by lxtnew** [comment]
找到问题原因了：因为 nginx 反向代理会自动把 http:// 变为 https://， 所以在配置中要加上：

**Comment by helloxz** [comment]
感谢您的反馈和分享。
