### ISSUE TITLE
更改favicon为本地

### ISSUE THREAD

**Issue by weiyidu** [helloxz/onenav#13]
代码中的获取不了，自己在网上找了方法修改了一下。
源码 https://github.com/owen0o0/getFavicon

效果 https://www.daohangweb.com

在模版index.php中找到如下代码：
`<img src="https://favicon.rss.ink/v1/<?php echo base64($link['url']); ?>" alt="HUAN" width="16" height="16" />
修改成
<img src="/favicon/<?php echo $link['url']; ?>" alt="HUAN" width="16" height="16" />
`
另外也建议把一些在线的css文件都改成本。

**Comment by helloxz** [comment]
1. 后续会考虑css/js完全离线
2. favicon离线我先看一下

**Comment by weiyidu** [comment]
> 1. 后续会考虑css/js完全离线
> 2. favicon离线我先看一下

操作后台时发现可以批量选择，好像是没有批量删除。

**Comment by weiyidu** [comment]
> 1. 后续会考虑css/js完全离线
> 2. favicon离线我先看一下

如果能支持多级目录就更妙了

**Comment by woodxi** [comment]
> 代码中的获取不了，自己在网上找了方法修改了一下。
> 源码https://github.com/owen0o0/getFavicon
> 
> 效果https://www.daohangweb.com
> 
> 在模版index.php中找到如下代码：另外
> `<img src="https://favicon.rss.ink/v1/<?php echo base64($link['url']); ?>" alt="HUAN" width="16" height="16" /> 修改成 <img src="/favicon/<?php echo $link['url']; ?>" alt="HUAN" width="16" height="16" /> `
> 也建议把一些在线的css文件都改成本。

**Comment by woodxi** [comment]
楼上的大神，你那个页面很棒，不知道能否共享源码！谢谢了

**Comment by weiyidu** [comment]
> 楼上的大神，你那个页面很棒，不知道能否共享源码！谢谢了

https://hostloc.com/thread-831766-1-1.html

**Comment by xiaojiacdn** [comment]
> 1. 后续会考虑css/js完全离线
> 2. favicon离线我先看一下

css/js 完全離綫的話，會不會相對很慢，或許可以用 jsdelivr 給靜態資源加速
favicon 有些獲取不了的話，我覺得可以給個默認的（個人想法）

**Comment by xvzhenduo** [comment]
> > 楼上的大神，你那个页面很棒，不知道能否共享源码！谢谢了
> 
> https://hostloc.com/thread-831766-1-1.html

那是网上一个价格大概200的主题，链接https://www.iotheme.cn/store/onenav.html

**Comment by weiyidu** [comment]
> > > 楼上的大神，你那个页面很棒，不知道能否共享源码！谢谢了
> > 
> > 
> > https://hostloc.com/thread-831766-1-1.html
> 
> 那是网上一个价格大概200的主题，链接https://www.iotheme.cn/store/onenav.html

已经共享了，蓝奏云域名改了
https://weiyidu.lanzoui.com/i42Pzo0qqhi

**Comment by helloxz** [comment]
`0.9.20`的默认主题已经支持离线图标（使用标题第一个字母作为图标）
