### ISSUE TITLE
请求增加密码功能

### ISSUE THREAD

**Issue by ma3252788** [helloxz/onenav#131]
目前私有是只能管理员登录才能看到，但是有时候会发给朋友，希望能增加输入密码查看的功能。

目前的分享加密码的功能暂时解决不了这个问题。

谢谢。

**Comment by helloxz** [comment]
可以在后台 - 链接管理 - 书签分享，可以对某个分类进行分享并设置密码访问，您看下是否满足需求。

**Comment by ma3252788** [comment]
> 可以在后台 - 链接管理 - 书签分享，可以对某个分类进行分享并设置密码访问，您看下是否满足需求。

感谢回复。这个只能给朋友分享特定的分类。希望能够实现公开首页之后，只需要给朋友密码，就能在访问所有分类的前提下，访问加密的分类。

**Comment by ma3252788** [comment]
比如我在一台公共的电脑上打开书签主页，我想访问某个分类下的网站，但是因为安全问题，不想登录账号。此时，给分类加密码就非常方便了

**Comment by helloxz** [comment]
通过上面的“后台 - 链接管理 - 书签分享，可以对某个分类进行分享并设置密码访问”应该可以满足你的要求。
