### ISSUE TITLE
关于主题

### ISSUE THREAD

**Issue by Felmon** [helloxz/onenav#132]
都私有化部署了为什么主题下载安装还要订阅的？
我看那些主题不都是开源的吗？
不就在template里多几个文件夹吗？
放在github这还能扯到服务器存储和带宽？
溜~

**Comment by helloxz** [comment]
主题非强制订阅，您可以去：https://soft.xiaoz.org/#/public/onenav/themes 手动下载主题。

不是所有用户的网络都能访问Github，所以订阅用户可以从最优网络直接一键下载主题。非订阅用户依然可以手动下载，感谢支持。

**Comment by Felmon** [comment]
sorry，我给你道个歉~
确实没注意看有手动下载主题的入口~
感谢分享及制作这个项目~

**Comment by helloxz** [comment]
> sorry，我给你道个歉~ 确实没注意看有手动下载主题的入口~ 感谢分享及制作这个项目~

客气了，在文档里面提到了手动下载主题的链接，后台没有写，所以不太显眼。感谢支持，祝您生活愉快。
