### ISSUE TITLE
手机可以访问，电脑无法访问

### ISSUE THREAD

**Issue by cnliucheng** [helloxz/onenav#135]
宝塔面板一键部署，ios可以正常访问，电脑浏览器却打不开网页，同样的网络环境

**Comment by helloxz** [comment]
我这边使用PC浏览器测试打开没有问题，建议您先自查下自身的网络环境，可尝试ping等命令进行测试。另外注意你网站似乎没有部署SSL，因此不支持https访问，需要检查PC访问的时候是否带上了https，如还有疑问，请提供完整报错截图，感谢支持！

![image](https://user-images.githubusercontent.com/7276531/221334215-a5f9d3e5-2c9c-4883-bb4c-3658aeedaa12.png)
