### ISSUE TITLE
edge 浏览器扩展打开速度非常慢，每次点击都会卡10秒左右

### ISSUE THREAD

**Issue by stkroot** [helloxz/onenav#139]
浏览器：Edge
onenav：通过 docker 架设，群晖docker
网络：局域网

点击扩展大概等10秒才会弹出界面，弹出后各功能正常，但每次点击扩展都会卡10秒才运行。

Edge 扩展管理里总是显示“服务工作进程 (不活动)”

OneNav 0.9.24
基于PHP + SQLite3开发的开源书签管理系统。
IDomlkjgkogkfpjbdigianpdbjncdchdco  检查视图  服务工作进程 (不活动)

**Comment by stkroot** [comment]
测试发现：
书签稍微多一点(比如20+)，浏览器中扩展点击“刷新数据”后，下次开始就会卡10秒。
删除书签后，浏览器扩展再“刷新数据”，则下次启动就正常了。
但再增加书签，如果再点击“刷新数据”，又必卡10秒。

**Comment by helloxz** [comment]
前端一次性全部渲染，存在性能问题，后续将进行优化，感谢支持。

**Comment by snailg** [comment]
> 测试发现： 书签稍微多一点(比如20+)，浏览器中扩展点击“刷新数据”后，下次开始就会卡10秒。 删除书签后，浏览器扩展再“刷新数据”，则下次启动就正常了。 但再增加书签，如果再点击“刷新数据”，又必卡10秒。

20+就卡了么？我2000+还能用么？

**Comment by helloxz** [comment]
> > 测试发现： 书签稍微多一点(比如20+)，浏览器中扩展点击“刷新数据”后，下次开始就会卡10秒。 删除书签后，浏览器扩展再“刷新数据”，则下次启动就正常了。 但再增加书签，如果再点击“刷新数据”，又必卡10秒。
> 
> 20+就卡了么？我2000+还能用么？

20+不至于，我200来个都还算正常。另外重构的Chrome扩展已经提交审核了，预计下周就能用上了，性能上有明显改进。

**Comment by helloxz** [comment]
已经发布重构版扩展，见Chrome Store：https://dwz.ovh/4kxn2

请将OneNav更新到最新的`0.9.32`版本，然后配合扩展使用。性能有明显的改善。
