### ISSUE TITLE
安卓平板点击右上角后台管理无法显示（重定向bug）

### ISSUE THREAD

**Issue by fuguangly** [helloxz/onenav#142]
阅读源码发现问题在的onenav/functions/helper.php108行位置，按照注释理解应该是/index.php?c=mobile，没有测试确认，反馈下。
https://github.com/helloxz/onenav/blob/bd4f71990dce6979405bfd4d882aa51baad519e2/functions/helper.php#L108

**Comment by helloxz** [comment]
下个版本进行修复

**Comment by helloxz** [comment]
`0.9.30`版本已经修复，见：https://github.com/helloxz/onenav/releases
