### ISSUE TITLE
前端渲染能优化吗

### ISSUE THREAD

**Issue by Durianyang** [helloxz/onenav#143]
我导入了1000+的书签，前端一次性渲染完所有分类实在是太卡了。
如果能按照分类渲染能好很多，再配合懒加载就最好了

**Comment by helloxz** [comment]
这个问题已经在优化中了，下个版本部分主题会解决这个问题。敬请关注！

**Comment by helloxz** [comment]
`0.9.30`已经优化这个问题，【后台 - 系统设置 - 站点设置】可设置链接数量（指的是首页单个分类下需要展示的链接数量，默认20，值越低，性能越好），见：https://github.com/helloxz/onenav/releases
