### ISSUE TITLE
提示有0.9.30更新，但是无可用版本

### ISSUE THREAD

**Issue by ausmas** [helloxz/onenav#147]
提示有0.9.30更新，但是一键更新中无可用版本

![image](https://github.com/helloxz/onenav/assets/2168423/b381a8d9-c228-4bbd-aab2-5c0ed06fda6f)

**Comment by helloxz** [comment]
你是部署在国外服务器上的吗？

**Comment by ausmas** [comment]
打扰了，好像是xiaoz.top被公司上网行为拦了……

**Comment by ausmas** [comment]
对你没记错。。你说的类似的用户也是我😂，但是我记得之前我把自己电脑放行了，之前还更新过来着，最近一直没更新，今天才发现又不能用了
