### ISSUE TITLE
armv7架构拉取docker镜像失败

### ISSUE THREAD

**Issue by bigmouse0001** [helloxz/onenav#148]
root@hinas:~# 
```
docker run -itd --name="onenav" -p 5543:80 \
>     -v /data/onenav:/data/wwwroot/default/data \
>     helloz/onenav
Unable to find image 'helloz/onenav:latest' locally
latest: Pulling from helloz/onenav
```

```
latest: Pulling from helloz/onenav
339de151aab4: Pull complete 
4f4fb700ef54: Pull complete 
64e2d91f6a6b: Pull complete 
aedf58cb2c7e: Pull complete 
03e9996f76bb: Pull complete 
16141d74ea3a: Pull complete 
Digest: sha256:da1030a7d0b01f3918f7806eef984f686d3578e4de34d592fb4f956341b6a741
Status: Downloaded newer image for helloz/onenav:latest
```

**WARNING**: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
a2cb98421c8b1892807eb6ac1ad33b34dc524b4c9a9a8b208ca56952df2252a2
![image](https://github.com/helloxz/onenav/assets/119995454/132f060b-51d3-455e-a034-b2cc6dbe158e)

问：在dockerhub上面看到是支持armv7/arm64的，但是拉取完成后提示只支持amd64

**Comment by helloxz** [comment]
是否使用了一些国内的Dcoker镜像，导致latest被缓存呢？在早期的`latest`中是不支持ARM的，后期已经支持ARM了，但如果被国内镜像缓存可能导致不支持。

**Comment by bigmouse0001** [comment]
我应该更换国外的docker镜像源吗？

**Comment by helloxz** [comment]
你可以试试指定tag为`0.9.30`或者`0.9.29`是否能够拉取到，如果拉取不到的话建议先更换Docker官方镜像试试。

**Comment by bigmouse0001** [comment]
好的，我再试试您的方法，谢谢 : )

**Comment by bigmouse0001** [comment]
拉取0.9.30版镜像后可以运行了，谢谢您！

**Comment by helloxz** [comment]
不客气。
