### ISSUE TITLE
几个优化建议

### ISSUE THREAD

**Issue by ausmas** [helloxz/onenav#149]
1. 后台新增的链接数量，不设置或设置为0时不知道是按默认20显示还是不限制，建议在提示中明确下
2. 当分类中链接数量小于设置的显示数量，或者设置为不限制（如有），前端不显示`>>`这个图标
3. 当分类下没有子分类时，侧边栏不显示展开箭头，让前端更简洁

**Comment by helloxz** [comment]
1. 不设置则为默认20，设置为0，则一个都不显示，后续我在提示中进行明确提醒
2. 这个我在下一个版本中进一步优化
3. 后续的版本中优化
感谢建议。

**Comment by ausmas** [comment]
> 1. 设置为0，则一个都不显示

测试设置为0时没变化，仍然显示

**Comment by awinds** [comment]
@helloxz
建议：我自己改了一下，在前端分类标题后不显示`更多>>`这个，如果不满20（设置数）则不显示，如果满或多的时候显示在下面的url格式最后一个，我改了下baisuTwo的主题，因为没有开源所以没有pull requests

**Comment by helloxz** [comment]
> @helloxz 建议：我自己改了一下，在前端分类标题后不显示`更多>>`这个，如果不满20（设置数）则不显示，如果满或多的时候显示在下面的url格式最后一个，我改了下baisuTwo的主题，因为没有开源所以没有pull requests

已完成优化，见：https://github.com/helloxz/onenav/releases/tag/0.9.31
