### ISSUE TITLE
移动端进入管理页面显示问题

### ISSUE THREAD

**Issue by ldxw** [helloxz/onenav#15]
![Screenshot_20210414_233955](https://user-images.githubusercontent.com/25827746/114738936-0546db00-9d7b-11eb-9679-aa5ed1efd263.jpg)
左边侧栏无法缩进，导致右边显示不全，是我手机问题吗？

**Comment by helloxz** [comment]
管理页面没有对移动设备适配，建议用电脑操作，你头像不错。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Mr.Lin ***@***.***>
Sent: Wednesday, April 14, 2021 11:43:26 PM
To: helloxz/onenav ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [helloxz/onenav] 移动端进入管理页面显示问题 (#15)


[Screenshot_20210414_233955]<https://user-images.githubusercontent.com/25827746/114738936-0546db00-9d7b-11eb-9679-aa5ed1efd263.jpg>
左边侧栏无法缩进，导致右边显示不全，是我手机问题吗？

―
