### ISSUE TITLE
点击更多后,无法通过左侧分类栏切换分类

### ISSUE THREAD

**Issue by wanyunr** [helloxz/onenav#150]
有一个分类是的链接 `/index.php?cid=21`，如果这个时候点击一个链接为`/index.php?cid=22`的分类，这时就会变为`/index.php?cid=21#category-22`，但不会切换分类。
![image](https://github.com/helloxz/onenav/assets/105478325/d02dc1a4-196f-4070-805a-68b7ea988f9b)

另外如果书签数量没有达到首页单个分类下需要展示的链接数量，可以不显示更多的按钮吗

**Comment by helloxz** [comment]
收到，下个版本进行优化。

**Comment by sevensevenmi** [comment]
我也遇到

**Comment by helloxz** [comment]
最新发布的`0.9.31`版本针对此情况做了优化处理，更新内容见：https://github.com/helloxz/onenav/releases/tag/0.9.31

建议主程序更新到最新的`0.9.31`，同时主题也更新到最新版本。
