### ISSUE TITLE
baisuNew - 1.0.0 主题不适配安卓移动端

### ISSUE THREAD

**Issue by baixing99** [helloxz/onenav#153]
baisuNew - 1.0.0 安卓手机访问都挤在一起了
![9018E79F4C52EF3DB31FD46B6AC93AFF](https://github.com/helloxz/onenav/assets/73473087/a0c9d0ce-92d6-495e-8ed9-212c5a3365aa)

**Comment by baixing99** [comment]
希望能修复一下

**Comment by helloxz** [comment]
这个是已知的，见发布说明：https://github.com/helloxz/onenav/releases 主题作者在开发的时候没有考虑适配移动端。

后续我会和作者共同努力适配手机访问，感谢支持。

**Comment by baixing99** [comment]
谢谢 希望尽快解决很喜欢onenav
