### ISSUE TITLE
一个适合多级标签的模版

### ISSUE THREAD

**Issue by ma3252788** [helloxz/onenav#154]
找到一个感觉非常适合多级标签的模版，是个纯静态的，请问大佬能否改装改装，感觉这个非常合适~
[https://ypyssl.machunjie.com/nav.html](https://ypyssl.machunjie.com/nav.html)

这个源码本来是用于列出本地文件的，但是如果把它改成书签，感觉也非常合适~

**Comment by helloxz** [comment]
这个感觉好古老啊，比较小众，暂时不会考虑适配到主题。感谢支持。
