### ISSUE TITLE
是否不支持.app后缀域名

### ISSUE THREAD

**Issue by kun775** [helloxz/onenav#155]
我添加一个.app后缀的域名，虽然能添加成功，后台我的链接显示也是app后缀的域名，但是前台和编辑页面会变成其他后缀的域名
我的链接显示正常
![121](https://github.com/helloxz/onenav/assets/12853372/1ea8c8fa-076b-4f81-a383-aef52a334dbd)

编辑页面url又变成其他域名了
![122](https://github.com/helloxz/onenav/assets/12853372/559dd6f4-086a-4b60-bcb3-acf32001ca2c)

前台显示也是变了
![133](https://github.com/helloxz/onenav/assets/12853372/ed71cef3-f8ad-4826-a038-8fba24d9bebb)

**Comment by helloxz** [comment]
未能复现这个问题，你是不是Nginx之类的启用了关键词替换？

**Comment by kun775** [comment]
> 未能复现这个问题，你是不是Nginx之类的启用了关键词替换？

这么说的话，好像是nginx替换了，结案了，谢谢
