### ISSUE TITLE
已经安装最新版本，chrome插件仍然提示版本过低，测试通过，但是无法保存

### ISSUE THREAD

**Issue by Dev-Wiki** [helloxz/onenav#162]
如图所示

![image](https://github.com/helloxz/onenav/assets/12946956/fcbdac5e-c99c-4462-98ef-e5f88a020251)

![image](https://github.com/helloxz/onenav/assets/12946956/593ccea5-5ced-4300-9650-8fb96441c525)

**Comment by helloxz** [comment]
Chrome扩展最近重构了，需要将OneNav核心程序升级到最新发布的0.9.32版本才能使用，见：https://github.com/helloxz/onenav/releases/tag/0.9.32

**Comment by Dev-Wiki** [comment]
> Chrome扩展最近重构了，需要将OneNav核心程序升级到最新发布的0.9.32版本才能使用，见：https://github.com/helloxz/onenav/releases/tag/0.9.32

但是docker 最新版为 0.9.31

![image](https://github.com/helloxz/onenav/assets/12946956/1b62934c-bb8d-4445-b63b-67264e8ebb9a)

**Comment by helloxz** [comment]
稍等几分钟，docker镜像还没打完。

**Comment by helloxz** [comment]
docker镜像也打完了，可以更新试试。

**Comment by Dev-Wiki** [comment]
> docker镜像也打完了，可以更新试试。

好的 我测试一下

**Comment by Dev-Wiki** [comment]
![image](https://github.com/helloxz/onenav/assets/12946956/e2c18802-4e19-45c2-8f9a-ac3233018dda)

如果按照后台提示 配置为 http ，chrome插件会提示程序异常。使用https 正常。

**Comment by helloxz** [comment]
应该是docker部署的原因，docker部署源站其实没有https，然后你应该用了反向代理，反向代理的服务器配置了https

下个版本我优化下这里的检测方法。

**Comment by Dev-Wiki** [comment]
> 应该是docker部署的原因，docker部署源站其实没有https，然后你应该用了反向代理，反向代理的服务器配置了https
> 
> 下个版本我优化下这里的检测方法。

我这使用的 frp 做的 内网穿透

**Comment by Dev-Wiki** [comment]
最新版已经可以使用
