### ISSUE TITLE
自动获取的图标都无法正常显示

### ISSUE THREAD

**Issue by gitject** [helloxz/onenav#166]
请问一下，刚部署后，添加前几个链接的时候图标是能自动获取并显示的，过了一段时候后，自动获取的图标都无法正常显示，包括之前能正常显示的也都裂了。
![image](https://github.com/helloxz/onenav/assets/31369527/fdeff6d0-a4f7-4fdb-acce-165531ea9fda)
![image](https://github.com/helloxz/onenav/assets/31369527/527aea19-5df7-4798-8aa4-07b494229386)

**Comment by helloxz** [comment]
百度云加速CDN抽风导致，已处理恢复。
