### ISSUE TITLE
为什么这么卡？

### ISSUE THREAD

**Issue by a506488043** [helloxz/onenav#168]
这个导航应该是静态的吧，有这么卡的？2核2个G，2M宽带
![IMG_9947](https://github.com/helloxz/onenav/assets/16434125/9fab013d-9142-43e4-bde6-6ac61cd466b4)
![IMG_9948](https://github.com/helloxz/onenav/assets/16434125/a6b68adb-52b3-4bd6-97fc-d8d32a5ff171)

**Comment by helloxz** [comment]
非纯静态，建议检查下服务器负载，网络等是否正常。
另外你可以访问https://nav.rss.ink/ 这个网站测试下是否卡顿。

**Comment by a506488043** [comment]
> 非纯静态，建议检查下服务器负载，网络等是否正常。
> 另外你可以访问https://nav.rss.ink/ 这个网站测试下是否卡顿。

服务器负载正常，偶偶秒打开，多点几次就卡的不行。自己电脑上部署也是这种情况，10代i7，32G内存。这应该不是服务器和电脑配置问题吧。

**Comment by a506488043** [comment]
![IMG_9949](https://github.com/helloxz/onenav/assets/16434125/3a89480d-e6be-469f-b938-a0c8a3cc8dec)

**Comment by a506488043** [comment]
![IMG_9950](https://github.com/helloxz/onenav/assets/16434125/375fb8c4-cdc4-4829-8789-ce9a94c55e22)

**Comment by a506488043** [comment]
> 非纯静态，建议检查下服务器负载，网络等是否正常。 另外你可以访问https://nav.rss.ink/ 这个网站测试下是否卡顿。
这应该不是服务器的问题，本地电脑都是这样。
![image](https://github.com/helloxz/onenav/assets/16434125/61aedbd6-437f-4c2b-86e9-d4bfdb6aaf8e)

**Comment by helloxz** [comment]
> > 非纯静态，建议检查下服务器负载，网络等是否正常。 另外你可以访问https://nav.rss.ink/ 这个网站测试下是否卡顿。
> > 这应该不是服务器的问题，本地电脑都是这样。
> > ![image](https://user-images.githubusercontent.com/16434125/271261950-61aedbd6-437f-4c2b-86e9-d4bfdb6aaf8e.png)

你这个抓包来看存在明显异常，静态资源耗时都那么久，静态资源不经过PHP和程序处理的，建议排查下WEB服务方面的问题。

您可以通过以下方法来排除：
新建一个站点，存放一些简单的CSS/JS文件，不放任何PHP文件，然后访问静态文件测试。如果静态文件访问很慢，WEB服务器或网络方面问题比较大。

**Comment by a506488043** [comment]
> > > 非纯静态，建议检查下服务器负载，网络等是否正常。 另外你可以访问https://nav.rss.ink/ 这个网站测试下是否卡顿。
> > > 这应该不是服务器的问题，本地电脑都是这样。
> > > ![image](https://user-images.githubusercontent.com/16434125/271261950-61aedbd6-437f-4c2b-86e9-d4bfdb6aaf8e.png)
> 
> 你这个抓包来看存在明显异常，静态资源耗时都那么久，静态资源不经过PHP和程序处理的，建议排查下WEB服务方面的问题。
> 
> 您可以通过以下方法来排除： 新建一个站点，存放一些简单的CSS/JS文件，不放任何PHP文件，然后访问静态文件测试。如果静态文件访问很慢，WEB服务器或网络方面问题比较大。

试过，静态资源都是秒开的
![image](https://github.com/helloxz/onenav/assets/16434125/4381234d-acac-441d-bc99-dd2aff3a7093)

**Comment by helloxz** [comment]
> > > > 非纯静态，建议检查下服务器负载，网络等是否正常。 另外你可以访问https://nav.rss.ink/ 这个网站测试下是否卡顿。
> > > > 这应该不是服务器的问题，本地电脑都是这样。
> > > > ![image](https://user-images.githubusercontent.com/16434125/271261950-61aedbd6-437f-4c2b-86e9-d4bfdb6aaf8e.png)
> > 
> > 
> > 你这个抓包来看存在明显异常，静态资源耗时都那么久，静态资源不经过PHP和程序处理的，建议排查下WEB服务方面的问题。
> > 您可以通过以下方法来排除： 新建一个站点，存放一些简单的CSS/JS文件，不放任何PHP文件，然后访问静态文件测试。如果静态文件访问很慢，WEB服务器或网络方面问题比较大。
> 
> 试过，静态资源都是秒开的 ![image](https://user-images.githubusercontent.com/16434125/271275121-4381234d-acac-441d-bc99-dd2aff3a7093.png)

那你试试在OneNav站点下创建一个新的文件`tz.php`，内容为：
```php
<?php
phpinfo();
```

然后访问`http://你的域名/tz.php`试下是否卡顿，这是一个PHP最基础的探针函数，理论是是秒开的，如果您打开很慢，那么PHP环境可能存在异常，需要进一步通过日志分析PHP进程。

**Comment by a506488043** [comment]
> > > > > 非纯静态，建议检查下服务器负载，网络等是否正常。 另外你可以访问https://nav.rss.ink/ 这个网站测试下是否卡顿。
> > > > > 这应该不是服务器的问题，本地电脑都是这样。
> > > > > ![image](https://user-images.githubusercontent.com/16434125/271261950-61aedbd6-437f-4c2b-86e9-d4bfdb6aaf8e.png)
> > > 
> > > 
> > > 你这个抓包来看存在明显异常，静态资源耗时都那么久，静态资源不经过PHP和程序处理的，建议排查下WEB服务方面的问题。
> > > 您可以通过以下方法来排除： 新建一个站点，存放一些简单的CSS/JS文件，不放任何PHP文件，然后访问静态文件测试。如果静态文件访问很慢，WEB服务器或网络方面问题比较大。
> > 
> > 
> > 试过，静态资源都是秒开的 ![image](https://user-images.githubusercontent.com/16434125/271275121-4381234d-acac-441d-bc99-dd2aff3a7093.png)
> 
> 那你试试在OneNav站点下创建一个新的文件`tz.php`，内容为：
> 
> ```
> <?php
> phpinfo();
> ```
> 
> 然后访问`http://你的域名/tz.php`试下是否卡顿，这是一个PHP最基础的探针函数，理论是是秒开的，如果您打开很慢，那么PHP环境可能存在异常，需要进一步通过日志分析PHP进程。

tz.php文件放在哪里，我这时docker部署的。
其他web服务是秒打开的。
这个能把js和css放到CDN上吗？
