### ISSUE TITLE
安全漏洞-任意文件删除（Deletion of any document）

### ISSUE THREAD

**Issue by tpt11fb** [helloxz/onenav#176]
HTTP Request：
![1](https://github.com/helloxz/onenav/assets/80188324/8c14352b-d31e-400b-ac50-a8686dde2a49)

/class/Api.php代码imp_link方法的$filename参数在调用unlink函数之前未作充分过滤。(The $filename parameter of the imp_link method of the /class/Api.php code was not sufficiently filtered before the unlink function was called.)
![image](https://github.com/helloxz/onenav/assets/80188324/bae484b7-372d-418c-90c5-583c8898d046)
过滤了../和./后直接使用。(Filtered... /and. / and use them directly)
![image](https://github.com/helloxz/onenav/assets/80188324/5935e5ca-8497-4cb9-a45e-867b86363f7a)

**Comment by helloxz** [comment]
感谢您的反馈，`0.9.34`已修复此漏洞。
