### ISSUE TITLE
上传图标功能不好使

### ISSUE THREAD

**Issue by WTIFS** [helloxz/onenav#179]
这里上传了一个图标，在后台能显示：
<img width="1504" alt="image" src="https://github.com/helloxz/onenav/assets/9314475/e403fc41-aefa-42e2-8c7c-0231386a8b8e">

但在前台不显示：
<img width="1181" alt="image" src="https://github.com/helloxz/onenav/assets/9314475/d84bde80-c9c6-4084-b1fd-0c020b04b8ad">

**Comment by helloxz** [comment]
这个主题不支持自定义图标，支持自定义的图标有`5iux/heimdall/tushan2/webstack`，且部分主题需要在主题参数设置里面开启。
