### ISSUE TITLE
OneNav主题天气显示问题

### ISSUE THREAD

**Issue by huqingyun6969** [helloxz/onenav#188]
域名：https://favorite.huqingyun.top
--------------------------------------
baisuNew 主题中右上角天气预报有问题，显示很丑，尽快解决
![image](https://github.com/helloxz/onenav/assets/162695992/2d0ce188-d48d-4785-b22d-14585814a4c0)

**Comment by helloxz** [comment]
原因是和风天气widget插件下架引起，见：[https://blog.qweather.com/announce/widget-v1-v2-will-be-closed-soon/](https://blog.qweather.com/announce/widget-v1-v2-will-be-closed-soon/)

目前受影响的2个主题`baisuNew`和`baisuTwo`已改用微博热榜替代天气插件，请在OneNav后台更新主题即可。
