### ISSUE TITLE
docker安装时，主题目录在哪里

### ISSUE THREAD

**Issue by woshichenghaibo** [helloxz/onenav#190]
想自己写个标题

**Comment by helloxz** [comment]
> > 在挂载路径的`templates`目录下，如果没有这个目录则自行创建即可，可参考这个说明：https://doc.xiaoz.org/books/onenav/page/7f100
> 
> /data/onenav/templates/ 新建这个路径吗？

挂载路径是你自己设置的，我并不清楚您设置的路径是哪个，如果您参考教程：[https://doc.xiaoz.org/books/onenav/page/a1d0c#bkmrk-docker%E5%AE%89%E8%A3%85](https://doc.xiaoz.org/books/onenav/page/a1d0c#bkmrk-docker%E5%AE%89%E8%A3%85)安装的，且没有去修改过任何路径，那么挂载路径就是`/data/onenav`，如果修改过，你就要看下容器详细信息来确认了。

**Comment by woshichenghaibo** [comment]
> /data/onenav/templates/

测试成功  nav.guao.de

**Comment by woshichenghaibo** [comment]
> /data/onenav/templates/

测试成功  nav.guao.de

**Comment by woshichenghaibo** [comment]
> > > 在挂载路径的`templates`目录下，如果没有这个目录则自行创建即可，可参考这个说明：https://doc.xiaoz.org/books/onenav/page/7f100
> > 
> > 
> > /data/onenav/templates/ 新建这个路径吗？
> 
> 挂载路径是你自己设置的，我并不清楚您设置的路径是哪个，如果您参考教程：https://doc.xiaoz.org/books/onenav/page/a1d0c#bkmrk-docker%E5%AE%89%E8%A3%85安装的，且没有去修改过任何路径，那么挂载路径就是`/data/onenav`，如果修改过，你就要看下容器详细信息来确认了。

请教，容器内部的路径怎么找，我想修改你默认主题的配置

**Comment by helloxz** [comment]
> > > > 在挂载路径的`templates`目录下，如果没有这个目录则自行创建即可，可参考这个说明：https://doc.xiaoz.org/books/onenav/page/7f100
> > > 
> > > 
> > > /data/onenav/templates/ 新建这个路径吗？
> > 
> > 
> > 挂载路径是你自己设置的，我并不清楚您设置的路径是哪个，如果您参考教程：[https://doc.xiaoz.org/books/onenav/page/a1d0c#bkmrk-docker%E5%AE%89%E8%A3%85安装的，且没有去修改过任何路径，那么挂载路径就是`/data/onenav`，如果修改过，你就要看下容器详细信息来确认了。](https://doc.xiaoz.org/books/onenav/page/a1d0c#bkmrk-docker%E5%AE%89%E8%A3%85%E5%AE%89%E8%A3%85%E7%9A%84%EF%BC%8C%E4%B8%94%E6%B2%A1%E6%9C%89%E5%8E%BB%E4%BF%AE%E6%94%B9%E8%BF%87%E4%BB%BB%E4%BD%95%E8%B7%AF%E5%BE%84%EF%BC%8C%E9%82%A3%E4%B9%88%E6%8C%82%E8%BD%BD%E8%B7%AF%E5%BE%84%E5%B0%B1%E6%98%AF%60/data/onenav%60%EF%BC%8C%E5%A6%82%E6%9E%9C%E4%BF%AE%E6%94%B9%E8%BF%87%EF%BC%8C%E4%BD%A0%E5%B0%B1%E8%A6%81%E7%9C%8B%E4%B8%8B%E5%AE%B9%E5%99%A8%E8%AF%A6%E7%BB%86%E4%BF%A1%E6%81%AF%E6%9D%A5%E7%A1%AE%E8%AE%A4%E4%BA%86%E3%80%82)
> 
> 请教，容器内部的路径怎么找，我想修改你默认主题的配置

容器内部的OneNav路径在`/data/wwwroot/default`里面。修改默认主题的话，你直接从Github下载整个源码，修改`templates/default`，然后上传到容器的`templates`下就行了。
