### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by DEKVIW** [helloxz/onenav#204]
onenav导入30000多个链接后卡的不行，搜索直接崩掉，部分主题直接不显示任何分类和数据。感觉也不是机器性能问题,，机器3核4g

**Comment by helloxz** [comment]
你这个有点狠，应该前后端未对这么大量的数据做优化。一般情况1000个左右没问题。95%的人应该都达不到1000个，你可以暂时先本地去掉一些不需要的链接。

后续我这边考虑用分页来优化你这种大量链接的情况。
