### ISSUE TITLE
favicon拼接判断有问题

### ISSUE THREAD

**Issue by arschlochnop** [helloxz/onenav#210]
现在只支持本地路径，或者通过手工上传自动补全路径如下：
![image](https://github.com/user-attachments/assets/7cda8130-c543-40ad-a3d8-957c1e6fed83)
不过`图标链接`还是有很大误解，我最开始添加的远程地址,这样首页会拼接失败。
![image](https://github.com/user-attachments/assets/85a727fb-a288-490d-8030-3cbd84cbd9ba)

建议把`手工上传`和`图标链接`功能分开，现在功能上是重叠的.
`手工上传`：上传图片文件
`图标链接`：输入远程链接

因为我都是配置远程favicon链接，直接比较粗暴的在主题js中替换就好了
```
sed -i 's|n\.domain+"/"+||g' /templates/default2/assets/index.js
```

**Comment by helloxz** [comment]
感谢反馈，`default2`主题已经发布`1.2.5`版本修复这个问题，可在后台在线更新此主题，或者等待下一个OneNav主板本发布的时候一起更新。
