### ISSUE TITLE
disclosure of information about sqlite

### ISSUE THREAD

**Issue by mcblog** [helloxz/onenav#25]
# disclosure of information about sqlite
### I download this cms and i first install it .
![a_20210804164034](https://user-images.githubusercontent.com/30430287/128150472-f0187242-6fe0-4491-a25a-e4293f70b86a.png)

# index.php:
```
if( !file_exists('./data/config.php') ) {
	exit('<h3>配置文件不存在，请将站点目录下的config.simple.php复制为data/config.php</h3>');
}
//检查数据库是否存在，不存在则复制数据库
if( !file_exists('./data/onenav.db3') ) {
	copy('db/onenav.simple.db3','data/onenav.db3');
	// copy('db/.htaccess','data/.htaccess');
}

//载入配置文件
require("./data/config.php");

//根据不同的请求载入不同的方法
//如果没有请求控制器
if((!isset($c)) || ($c == '')){
	//载入主页
    include_once("./controller/index.php");
    
}

else{
	include_once("./controller/".$c.'.php');
}
```
### bug code :
```
if( !file_exists('./data/onenav.db3') ) {
	copy('db/onenav.simple.db3','data/onenav.db3');
```
then i try to require "./data/onenav.db3" and "/data/.htaccess" http response status 200 

it means i can download onenav.db3 and 
![a0](https://user-images.githubusercontent.com/30430287/128151261-fb5f22b5-02f4-42ac-aa7e-9b69d40a8b9d.png)

can gets some  privacy information

### you can add some random code to document name or sqlite database name .

this cms has many users.

**Comment by helloxz** [comment]
hello,You can set things up to prevent the database from being downloaded.You can refer to this link: [https://www.yuque.com/helloz/onenav/install#ImLOx](https://www.yuque.com/helloz/onenav/install#ImLOx)
