### ISSUE TITLE
移动端无法看到登陆入口

### ISSUE THREAD

**Issue by GabrielGonGod** [helloxz/onenav#27]
如题，只有手动加上index.php?c=login才能登陆，并且登陆之后，菜单挤在一起了，难以点回首页
设备是ip12pm

**Comment by helloxz** [comment]
您好，后台管理并没有对移动端做适配，建议电脑操作。
在 2021年8月29日 +0800 00:51，GabrielGonGod ***@***.***>，写道：

**Comment by GabrielGonGod** [comment]
> 您好，后台管理并没有对移动端做适配，建议电脑操作。 在 2021年8月29日 +0800 00:51，GabrielGonGod ***@***.***>，写道：
> […](#)
> 如题，只有手动加上index.php?c=login才能登陆，并且登陆之后，菜单挤在一起了，难以点回首页 设备是ip12pm —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

hi，是这样的，这是有使用场景的。这个导航页有时候有很多私人页面，如果不登陆，就无法查看到。而这些页面有时候就是要经常在非PC端使用的

**Comment by helloxz** [comment]
您好，`0.9.13`版本的默认主题增加了一个手机登录按钮：[https://github.com/helloxz/onenav/releases](https://github.com/helloxz/onenav/releases)。手机访问的时候打开导航可以看到下面有个登录。
