### ISSUE TITLE
使用docker部署的话，怎么修改主题呢

### ISSUE THREAD

**Issue by mozidea** [helloxz/onenav#31]
使用docker部署的话，怎么修改主题呢

**Comment by mozidea** [comment]
自己搞定了！
:)

**Comment by banjuer** [comment]
新版.19 docker主题模板`templates`的对应挂载目录是啥呢

**Comment by helloxz** [comment]
你直接挂载data这个一个目录就行了，挂载后在你的挂载目录下自行新建一个`templates`,把主题放到`templates`下后台启用即可。
