### ISSUE TITLE
分类图标

### ISSUE THREAD

**Issue by xuzhibin** [helloxz/onenav#34]
前台分类前面的图标是在哪里设置的？

**Comment by helloxz** [comment]
用的Font Awesome 4图标，可参考文档说明：[https://doc.xiaoz.me/books/onenav/page/091d5#bkmrk-%E5%88%86%E7%B1%BB%E5%90%8D%E7%A7%B0%E5%9B%BE%E6%A0%87%E8%AE%BE%E7%BD%AE](https://doc.xiaoz.me/books/onenav/page/091d5#bkmrk-%E5%88%86%E7%B1%BB%E5%90%8D%E7%A7%B0%E5%9B%BE%E6%A0%87%E8%AE%BE%E7%BD%AE)

**Comment by xuzhibin** [comment]
明白了，谢谢。项目很好用。可以考虑出浏览器插件，配合使用应该更加方便，解决多浏览器书签同步问题

**Comment by helloxz** [comment]
后续会考虑浏览器插件，感谢支持。
