### ISSUE TITLE
希望能加个暗色模式

### ISSUE THREAD

**Issue by lockl** [helloxz/onenav#37]
现在已经做的很好了，就差个暗色模式（自动切换和手动切换按钮），现在晚上用太刺眼了

**Comment by xvzhenduo** [comment]
你可以看一下这个主题
https://gitee.com/baisucode/onenav-theme
暗色模式
![image](https://user-images.githubusercontent.com/74353173/150798930-e46ec958-5a4f-46f2-8849-f789112e01b9.png)
亮色模式
![image](https://user-images.githubusercontent.com/74353173/150798866-89476db4-0874-469f-b7a2-c90926813a66.png)

**Comment by helloxz** [comment]
您好，`0.9.19`的默认主题已经支持暗色模式，请升级即可，感谢支持。
