### ISSUE TITLE
arm64 docker部署helloz/onenav:dev-0.9.13报错

### ISSUE THREAD

**Issue by xinqinglhj** [helloxz/onenav#39]
2022/02/15 22:47:45 [alert] 13#13: setrlimit(RLIMIT_NOFILE, 100000) failed (1: Operation not permitted)

2022/02/15 22:47:45 [alert] 12#12: setrlimit(RLIMIT_NOFILE, 100000) failed (1: Operation not permitted)

2022/02/15 22:47:45 [alert] 14#14: setrlimit(RLIMIT_NOFILE, 100000) failed (1: Operation not permitted)

2022/02/15 22:47:45 [alert] 16#16: setrlimit(RLIMIT_NOFILE, 100000) failed (1: Operation not permitted)

**Comment by helloxz** [comment]
1. 检查下你的系统是否开启了Selinux
2. 看下挂载目录是不是权限不够

**Comment by xinqinglhj** [comment]
可以部署成功，启动容器时失败，报上面的错误,不能访问页面

> 部署后服务能打开吗？
> 
> 1. 检查下你的系统是否开启了Selinux
> 2. 看下挂载目录是不是权限不够
这两个问题，如果确认？

**Comment by helloxz** [comment]
你是NAS上的Docker还是自己安装的Docker啊，空了加我QQ：337003006，远程看下。

**Comment by xinqinglhj** [comment]
重启了一下 可以正常运行了，多谢。

**Comment by helloxz** [comment]
好的，问题解决了就好。
