### ISSUE TITLE
V0.9.13 分类设置图标不能识别

### ISSUE THREAD

**Issue by azucool** [helloxz/onenav#41]
![image](https://user-images.githubusercontent.com/8179008/154690756-0ec84cc7-84be-421e-a7cd-497dcb198bee.png)
全新安装的程序，出现此问题，不是模板原因 ，默认模板也不能识别，求解。

**Comment by tznb1** [comment]
修复方案: 
1.编辑/class/Api.php 如图所示,去除name的htmlspecialchars转换,并保存
2.重新添加分类!
注:作者应该是想防止XSS加的代码
![](https://s3.bmp.ovh/imgs/2022/02/6c67813bd2c1660e.jpg)
![](https://s3.bmp.ovh/imgs/2022/02/63302b50edca8b14.jpg)
'name'          =>  $name,

**Comment by helloxz** [comment]
请下载`0.9.14`版本升级覆盖可解决：[https://github.com/helloxz/onenav/releases/tag/0.9.14](https://github.com/helloxz/onenav/releases/tag/0.9.14)
