### ISSUE TITLE
V0.9.13 分类图标异常的修复方案 

### ISSUE THREAD

**Issue by tznb1** [helloxz/onenav#42]
修复方案: 
编辑/class/Api.php 如图所示,去除name的htmlspecialchars转换,并保存
搜索 `htmlspecialchars($name,ENT_QUOTES)`
提替换为 `$name`
重新添加分类或者进入编辑重新保存!
注:作者应该是想防止XSS加的代码
![](https://s3.bmp.ovh/imgs/2022/02/6c67813bd2c1660e.jpg)
![](https://s3.bmp.ovh/imgs/2022/02/63302b50edca8b14.jpg)

或者在主题模板添加相应的解码函数.
文件 /templates/default/index.php
搜索 `<?php echo $category['name']; ?>`
替换为`<?php echo htmlspecialchars_decode($category['name']); ?>`
如果有其他主题,都需要修改一遍!

**Comment by helloxz** [comment]
感谢大佬贡献，我先自测一下这样是否还会XSS

**Comment by helloxz** [comment]
验证有效，已在`0.9.14`解决，感谢贡献。
