### ISSUE TITLE
我的链接可以批量导出，那能不能批量导入。

### ISSUE THREAD

**Issue by wangshiw** [helloxz/onenav#46]
从书签导入后还需要重新调整分类，在表格中可以直接设置好分类，权重等，比较方便。

**Comment by Jayin** [comment]
批量设置分类、权重 可以快速大部分需求 #65

**Comment by helloxz** [comment]
请参考最新发布的`0.9.21`版本，支持导入导出：[https://github.com/helloxz/onenav/releases/tag/0.9.21](https://github.com/helloxz/onenav/releases/tag/0.9.21)
