### ISSUE TITLE
增加全局密码登陆功能

### ISSUE THREAD

**Issue by Omoinemie** [helloxz/onenav#5]
私人书签不想他人看到，增加一个全局登陆用户和密码，进后台就不需要密码

**Comment by helloxz** [comment]
正在考虑支持只读用户访问

**Comment by LiteCoder** [comment]
请问这个feature实现了吗

**Comment by helloxz** [comment]
> > 正在考虑支持只读用户访问
> 
> 请问这个feature实现了吗

最新版支持书签分享功能，可以将私有书签以设置密码的方式分享给朋友。
