### ISSUE TITLE
建议增加一个网址有效性检测

### ISSUE THREAD

**Issue by ZergBoy** [helloxz/onenav#52]
我的链接右上角那位置挺适合的

**Comment by acloudtwei** [comment]
这个我也建议，很重要，也不难噢

**Comment by helloxz** [comment]
有些是内网地址或者被墙的地址，这种检测结果不太准确，意义不大。

**Comment by snailg** [comment]
> 有些是内网地址或者被墙的地址，这种检测结果不太准确，意义不大。

还是有用的，有些时间久了变404了   书签比较多的情况下 不容易发现

**Comment by helloxz** [comment]
好的，既然那么多人都需要，那我后面安排下。

**Comment by yohaneowo** [comment]
支持! :D

**Comment by yohaneowo** [comment]
支持! :D

**Comment by helloxz** [comment]
`1.0.0`版本已经支持，见：[https://github.com/helloxz/onenav/releases/tag/1.0.0](https://github.com/helloxz/onenav/releases/tag/1.0.0)

![](https://img.rss.ink/imgs/2024/12/17/5da1a673eeec6b1c.png)
