### ISSUE TITLE
数据接口请求异常：parsererror

### ISSUE THREAD

**Issue by wu529778790** [helloxz/onenav#57]
分类接口

数据接口请求异常：parsererror

**Comment by helloxz** [comment]
1. 数据库目录权限是否可读写呢？
2. 浏览器F12抓包看下详细错误是什么。

**Comment by wu529778790** [comment]
> 1. 数据库目录权限是否可读写呢？
> 2. 浏览器F12抓包看下详细错误是什么。

权限都是755，

`<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function fetchAll() on boolean in /www/wwwroot/nav.shenzjd.com/class/Api.php:439
Stack trace:
#0 /www/wwwroot/nav.shenzjd.com/controller/api.php(138): Api-&gt;category_list(1, 10)
#1 /www/wwwroot/nav.shenzjd.com/controller/api.php(22): category_list(Object(Api))
#2 /www/wwwroot/nav.shenzjd.com/index.php(54): include_once('/www/wwwroot/na...')
#3 {main}
  thrown in <b>/www/wwwroot/nav.shenzjd.com/class/Api.php</b> on line <b>439</b><br />`

**Comment by helloxz** [comment]
你PHP版本是多少呢，感觉是PHP版本低了，要求是`5.6-7.4`

**Comment by wu529778790** [comment]
> 你PHP版本是多少呢，感觉是PHP版本低了，要求是`5.6-7.4`

7.2 7.4都试过了

**Comment by helloxz** [comment]
直接加我QQ：337003006，远程看。

**Comment by wu529778790** [comment]
/data/onenav.db3

这个接口403

**Comment by wu529778790** [comment]
> 337003006

暂时没法上扣扣，回去了联系

**Comment by helloxz** [comment]
> /data/onenav.db3
> 
> 这个接口403

这个不是接口，这个是数据库，默认是禁止访问的，不是这个原因。

**Comment by helloxz** [comment]
您好，由于长时间未反馈，此问题关闭，如有问题请联系QQ:337003006
