### ISSUE TITLE
增加https支持?

### ISSUE THREAD

**Issue by pyy-Yanis** [helloxz/onenav#58]

**Comment by helloxz** [comment]
[是否支持https和程序没有关系（比我我的演示站：[https://nav.rss.ink/](https://nav.rss.ink/)），你需要在自己的WEB服务器上自己部署https

**Comment by pyy-Yanis** [comment]
我看docker镜像里面没开443端口吧?docker里面不开个443端口?

**Comment by helloxz** [comment]
不太建议直接在Docker上部署https，建议docker部署后通过nginx反向代理。比如您有多个站点，443端口已经被其它站点使用，docker就没法使用443端口，而只能用非标端口，这时用nginx统一反向代理非标端口集中式入口。
