### ISSUE TITLE
登陆后关闭浏览器后再进入不显示输入账号密码

### ISSUE THREAD

**Issue by Omoinemie** [helloxz/onenav#6]
这会有隐私泄露风险

**Comment by helloxz** [comment]
登录成功后设置的cookie在浏览器中保存7天，7天内同一个浏览器无需重复登陆，这是很常见的做法。可以理解保持登录功能（不过onenav没做成选项），仅仅是针对你这个已经登录过的浏览器而已。你换个从来没登录过的浏览器，或者使用隐私窗口打开看下就明白了。
