### ISSUE TITLE
批量设置分类、权重

### ISSUE THREAD

**Issue by Jayin** [helloxz/onenav#65]
链接有点多，移动起来麻烦
![image](https://user-images.githubusercontent.com/2763894/165347087-2d5f23c5-31ca-4902-a90f-81f8de451953.png)

**Comment by helloxz** [comment]
下个版本上线批量修改分类

**Comment by helloxz** [comment]
您好，`0.9.20`已经可以批量设置分类。备份数据后覆盖升级即可。批量设置权重可能暂时不会考虑。
