### ISSUE TITLE
页面书签搜索时，同时匹配URL

### ISSUE THREAD

**Issue by banjuer** [helloxz/onenav#68]

**Comment by helloxz** [comment]
默认主题在下个版本实现此功能。

**Comment by helloxz** [comment]
您好，默认主题已经支持，参考`0.9.21`版本：[0.9.21](https://github.com/helloxz/onenav/releases/tag/0.9.21)

**Comment by banjuer** [comment]
啥时候并到lastest分支啊，现在更新每次得手动pull指定版本号。😂

**Comment by helloxz** [comment]
lastest分支同步更新了的啊，如果你用了国内的docker镜像可能会有缓存。
![image](https://user-images.githubusercontent.com/7276531/168527819-9a827941-8aaf-46e6-aa4e-4e17e5d4e66b.png)
