### ISSUE TITLE
!!!大量数据查询耗时

### ISSUE THREAD

**Issue by kts168** [helloxz/onenav#69]
数据量大时，查询有些耗时，能不能做到按需检索，不要一次性全部检索

**Comment by helloxz** [comment]
SQLite 3上万的数据应该问题不大，性能瓶颈可能是前端，了解下您书签大概有多少呢？

**Comment by banjuer** [comment]
> SQLite 3上万的数据应该问题不大，性能瓶颈可能是前端，了解下您书签大概有多少呢？

页面上的搜索框，搜索是前端过滤的吧？

**Comment by helloxz** [comment]
> > SQLite 3上万的数据应该问题不大，性能瓶颈可能是前端，了解下您书签大概有多少呢？
> 
> 页面上的搜索框，搜索是前端过滤的吧？

是的，搜索框是前端实现，所以如果书签很多的情况下，搜索可能会存在性能问题。后续准备从后端实现。

**Comment by huanzhiyi** [comment]
> > > SQLite 3上万的数据应该问题不大，性能瓶颈可能是前端，了解下您书签大概有多少呢？
> > 
> > 
> > 页面上的搜索框，搜索是前端过滤的吧？
> 
> 是的，搜索框是前端实现，所以如果书签很多的情况下，搜索可能会存在性能问题。后续准备从后端实现。

请问以后会添加mysql之类的存储方式吗？

**Comment by helloxz** [comment]
> > > > SQLite 3上万的数据应该问题不大，性能瓶颈可能是前端，了解下您书签大概有多少呢？
> > > 
> > > 
> > > 页面上的搜索框，搜索是前端过滤的吧？
> > 
> > 
> > 是的，搜索框是前端实现，所以如果书签很多的情况下，搜索可能会存在性能问题。后续准备从后端实现。
> 
> 请问以后会添加mysql之类的存储方式吗？

定位是个人书签，SQLite足够使用了，而且更简单，暂时没有支持MySQL的计划，感谢支持。

**Comment by kts168** [comment]
closed
