### ISSUE TITLE
关于链接描述和链接url

### ISSUE THREAD

**Issue by kts168** [helloxz/onenav#70]
![Snipaste_2022-05-04_17-43-30](https://user-images.githubusercontent.com/2002728/166659177-afd49e8e-7a44-4978-ac82-70652d272293.png)
建议增加链接url展示功能 , 链接url和链接描述可以通过开关来配置是否显示

**Comment by helloxz** [comment]
您好，在`0.9.20`中已经实现了主题的自定义参数设置，可以参考帮助文档：[https://doc.xiaoz.me/books/onenav/page/13f3c](https://doc.xiaoz.me/books/onenav/page/13f3c) 进行关闭描述。

**Comment by kts168** [comment]
再加个 link_url 吧

**Comment by kts168** [comment]
再加个 link_url 吧 , 不用点击去就能看到网址了
