### ISSUE TITLE
部署在阿里云虚拟主机上无法使用

### ISSUE THREAD

**Issue by caihua** [helloxz/onenav#73]
部署在阿里云虚拟主机，看起来链接跳转有点问题，貌似是不支持.htacess文件。
现象是一直跳转到初始化设置密码页面。类似这样  xxx.com/?username=q&password=q&password2=q
我的部署方法是直接下载文件，解压上传到ftp
能否考虑设置在这种场景下，使用完整的url

**Comment by helloxz** [comment]
感觉像是目录权限不对，检查下`data`目录的权限呢，必须可读写。

**Comment by caihua** [comment]
不是目录权限的问题，可能是其他问题

**Comment by jackadam1981** [comment]
我在php8下，一进管理页，就GG了。
PHP版本兼容测试了么？

**Comment by helloxz** [comment]
> 我在php8下，一进管理页，就GG了。 PHP版本兼容测试了么？

帮助文档已经提到了不支持PHP 8:，参考：[https://doc.xiaoz.me/books/onenav/page/a1d0c](https://doc.xiaoz.me/books/onenav/page/a1d0c) ，下个版本我加个PHP检测，大于8直接不让安装。

**Comment by jackadam1981** [comment]
哦，我在github这里看readme没看到PHP版本要求，只看到了sqlite3

**Comment by jackadam1981** [comment]
据说8比7快了25%。

**Comment by helloxz** [comment]
> 据说8比7快了25%。

小项目不存在性能瓶颈，体验差距不明显，7已经够用了，没必要追求更新。很多线上的PHP项目可能还是5

**Comment by LinkArcher** [comment]
我更新后7.4都

> > > 我在php8下，一进管理页，就GG了。 PHP版本兼容测试了么？
> > 
> > 
> > 帮助文档已经提到了不支持PHP 8:，参考：https://doc.xiaoz.me/books/onenav/page/a1d0c ，下个版本我加个PHP检测，大于8直接不让安装。
> 
> 如果加检测，做安装，那就把组件检查，目录权限检查都可以加上。 小巧，我是装到openwrt路由器里面了。看了docker，才知道依赖有这些。 apk add php7 php7-fpm php7-openssl php7-sqlite3 php7-pdo_sqlite php7-curl php7-json php7-session

我直接更新站点文件，然后7.4也后台翻车了，给我整闷了。。还有别的依赖也会导致后台访问就跪了
