### ISSUE TITLE
API问题

### ISSUE THREAD

**Issue by junono97** [helloxz/onenav#74]
使用c=api&method=add_link添加链接时候
为何总提示fid不存在？0和19都不行。
![image](https://user-images.githubusercontent.com/57182325/167308272-fdf79abb-4c4c-40ac-a1d4-8b3282813435.jpeg

**Comment by helloxz** [comment]
把你的请求体内容提供下呢，添加的时候是不是没提供`fid`这个参数啊？这个是分类ID

**Comment by junono97** [comment]
> 把你的请求体内容提供下呢，添加的时候是不是没提供`fid`这个参数啊？这个是分类ID

你好，我添加了，这是我写的捷径指令。对应的是domin.com/index.php?c=api&method=add_link&token=xx&url=xxx&title=xx&fid=xx
![image](https://user-images.githubusercontent.com/57182325/167465112-0be90352-7275-4a69-96fa-1beafc5c27d6.jpeg)。

**Comment by helloxz** [comment]
请求体不是json格式哦，是`form`表单格式。

**Comment by junono97** [comment]
非常感谢！> 请求体不是json格式哦，是`form`表单格式。

**Comment by helloxz** [comment]
我看你上面截图那里请求体是选择的`json`类型呢？
![image](https://user-images.githubusercontent.com/7276531/167528084-30a553a8-f925-4642-b8ee-86b39660c192.png)

**Comment by junono97** [comment]
> 我看你上面截图那里请求体是选择的`json`类型呢？
> 
> ![image](https://user-images.githubusercontent.com/7276531/167528084-30a553a8-f925-4642-b8ee-86b39660c192.png)
> 
> 

改为表单后可以添加了，谢谢！

**Comment by helloxz** [comment]
不客气，那此问题就关闭了。
