### ISSUE TITLE
静态文件未放入源码,无法内网部署

### ISSUE THREAD

**Issue by daioneone** [helloxz/onenav#8]
静态文件全都是连接到你的https://libs.xiaoz.top/ ,无法内网部署

**Comment by bluster2005** [comment]
你把静态文件下载下来，拖到本地目录，然后在源码里改地址不就行了

**Comment by helloxz** [comment]
如果熟悉一些前端的话可以将layui、mdui等下载下来然后修改为本地调用，后续出离线版本。
