### ISSUE TITLE
新安装时设置管理员用户出错

### ISSUE THREAD

**Issue by IILee5** [helloxz/onenav#80]
我已按照要求填写用户名，但依旧报错。
![image](https://user-images.githubusercontent.com/40862062/171103491-80d4e0b8-fad3-448d-98a1-208a3151a61e.png)

**Comment by helloxz** [comment]
检查下数据库目录data是否可读写，一般用root直接操作后站点目录权限可能出问题。

**Comment by IILee5** [comment]
您好，我这边已经给到最高权限了
![image](https://user-images.githubusercontent.com/40862062/171105266-0dc39052-c17a-47ef-b682-2d540d243b12.png)

**Comment by IILee5** [comment]
这是我编写的compose文件
![image](https://user-images.githubusercontent.com/40862062/171105392-f403f38a-7303-4f53-93fb-b6632d51929d.png)

**Comment by helloxz** [comment]
看了下代码：
```javascript
var u_patt = /^[0-9a-z]{3,32}$/;
if ( !u_patt.test(username) ) {
      layer.msg("用户名需要3-32位的字母或数字组合！", {icon: 5});
      return false;
    }
```

用户名需要纯小写，不要包含大写字母。

**Comment by IILee5** [comment]
好的明白了，感谢您的解答👍
