### ISSUE TITLE
查询此分类下的链接没有用

### ISSUE THREAD

**Issue by acloudtwei** [helloxz/onenav#82]
开发者你好，你这个功能并没有实现，我去查看了源码，发现只是写了一个空按钮，并没有实现里面的函数！

请开发更新一下，谢谢！

**Comment by acloudtwei** [comment]
不好意思，发现在js是写了对应的函数，但是没有用，无法检索特定分类下的数据

**Comment by acloudtwei** [comment]
我发现你这个接口没啥用index.php?c=api&method=link_list，不过加什么参数都是返回同样的数据，说明这个接口不太行，
我也不知道是因为那个token什么原因，还是希望开发者去查看下，修复bug

**Comment by helloxz** [comment]
抱歉，修复一个BUG的时候搞出新BUG了，下个版本修复。查询分类下的链接现在用新的API了：[https://doc.xiaoz.me/books/onenav/page/fc490](https://doc.xiaoz.me/books/onenav/page/fc490)

**Comment by helloxz** [comment]
已在`0.9.23`中修复：https://github.com/helloxz/onenav/releases/tag/0.9.23，感谢您的反馈。
