### ISSUE TITLE
主题写入失败，请检查目录权限！

### ISSUE THREAD

**Issue by banjuer** [helloxz/onenav#87]
环境：容器运行
版本：0.9.23
挂载目录：`/volume2/docker/onenav/data:/data/wwwroot/default/data `
复现：
点击下载任一在线主题，提示**主题写入失败，请检查目录权限！**
![image](https://user-images.githubusercontent.com/18739609/172845445-2ab2b49a-0311-4d12-9a8c-0b7ce09584b7.png)

**Comment by banjuer** [comment]
> 

在挂载的`/volume2/docker/onenav/data`子目录`templates`下有对应主题的大小为`0Bytes`的gz包，感觉像是为正常下载下来。
![image](https://user-images.githubusercontent.com/18739609/172846287-c036cd17-306b-46df-a26a-29a5a8c8f1c2.png)

**Comment by helloxz** [comment]
你是NAS的Docker吗？我VPS上的Docker未能复现，先给挂载目录的`templates`目录777权限再试试呢？

**Comment by banjuer** [comment]
`777`权限仍然不行，个人感觉应该不是权限的问题，因为`/data/wwwroot/default/data/templates`目录下已经有程序创建的主题`gz`文件，只不过大小为0.看起来像是下载失败了

> 你是NAS的Docker吗？我VPS上的Docker未能复现，先给挂载目录的`templates`目录777权限再试试呢？

**Comment by helloxz** [comment]
像是你说的这个问题，是部署服务器是哪里的呢？海外吗？

**Comment by banjuer** [comment]
不是的，就部署在家里，北京移动。等回家我再看一下是不是网络的
