### ISSUE TITLE
内置的baisuTwo左上角的logo不显示

### ISSUE THREAD

**Issue by ZDY321** [helloxz/onenav#95]
作者你好，我想问下，网站左上角的logo不显示该怎么解决啊，是默认的那个logo
![image](https://user-images.githubusercontent.com/81518210/182057481-7d563705-0aed-4af6-97f6-d9714dbb331d.png)

**Comment by helloxz** [comment]
你是不是加了我QQ啊，最近在QQ上解决了一个。是logo链接有防盗链导致，换个图床就好了。
