### ISSUE TITLE
图标获取失败

### ISSUE THREAD

**Issue by blueandstar** [helloxz/onenav#99]
看了一下其他人的，好像都挂了
![image](https://user-images.githubusercontent.com/105478325/193811631-492f79e3-ba4c-4841-bc30-6925cf9e2b6f.png)

**Comment by helloxz** [comment]
CDNl流量超标，已经处理了。另外部分主题支持离线图标，可参考：[https://doc.xiaoz.me/books/onenav/page/13f3c](https://doc.xiaoz.me/books/onenav/page/13f3c)，感谢支持。
